-- MySQL Script generated by MySQL Workbench
-- Wed Apr 28 23:11:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_progra4_proyecto1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_progra4_proyecto1` ;

-- -----------------------------------------------------
-- Schema db_progra4_proyecto1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_progra4_proyecto1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `db_progra4_proyecto1` ;

-- -----------------------------------------------------
-- Table `db_progra4_proyecto1`.`area_tematica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_progra4_proyecto1`.`area_tematica` ;

CREATE TABLE IF NOT EXISTS `db_progra4_proyecto1`.`area_tematica` (
  `id_area` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_progra4_proyecto1`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_progra4_proyecto1`.`curso` ;

CREATE TABLE IF NOT EXISTS `db_progra4_proyecto1`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `area_tematica_id` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_curso_area_tematica1_idx` (`area_tematica_id` ASC) VISIBLE,
  CONSTRAINT `fk_curso_area_tematica1`
    FOREIGN KEY (`area_tematica_id`)
    REFERENCES `db_progra4_proyecto1`.`area_tematica` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_progra4_proyecto1`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_progra4_proyecto1`.`rol` ;

CREATE TABLE IF NOT EXISTS `db_progra4_proyecto1`.`rol` (
  `id_rol` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_progra4_proyecto1`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_progra4_proyecto1`.`usuario` ;

CREATE TABLE IF NOT EXISTS `db_progra4_proyecto1`.`usuario` (
  `id_usuario` VARCHAR(45) NOT NULL,
  `rol_id` INT NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `ultimo_aceso` TIMESTAMP NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`id_usuario`, `rol_id`),
  INDEX `fk_usuario_rol_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `db_progra4_proyecto1`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_progra4_proyecto1`.`profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_progra4_proyecto1`.`profesor` ;

CREATE TABLE IF NOT EXISTS `db_progra4_proyecto1`.`profesor` (
  `id_profesor` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_profesor`),
  INDEX `fk_profesor_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_profesor_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_progra4_proyecto1`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_progra4_proyecto1`.`horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_progra4_proyecto1`.`horario` ;

CREATE TABLE IF NOT EXISTS `db_progra4_proyecto1`.`horario` (
  `seq` INT NOT NULL AUTO_INCREMENT,
  `dia` INT NOT NULL,
  `hora` INT NOT NULL,
  PRIMARY KEY (`seq`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_progra4_proyecto1`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_progra4_proyecto1`.`grupo` ;

CREATE TABLE IF NOT EXISTS `db_progra4_proyecto1`.`grupo` (
  `num_grupo` INT NOT NULL AUTO_INCREMENT,
  `curso_id` INT NOT NULL,
  `profesor_id` INT NOT NULL,
  `horario_seq` INT NOT NULL,
  PRIMARY KEY (`num_grupo`, `curso_id`),
  INDEX `fk_grupo_curso1_idx` (`curso_id` ASC) VISIBLE,
  INDEX `fk_grupo_profesor1_idx` (`profesor_id` ASC) VISIBLE,
  INDEX `fk_grupo_horario1_idx` (`horario_seq` ASC) VISIBLE,
  CONSTRAINT `fk_grupo_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `db_progra4_proyecto1`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_profesor1`
    FOREIGN KEY (`profesor_id`)
    REFERENCES `db_progra4_proyecto1`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_horario1`
    FOREIGN KEY (`horario_seq`)
    REFERENCES `db_progra4_proyecto1`.`horario` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_progra4_proyecto1`.`estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_progra4_proyecto1`.`estudiante` ;

CREATE TABLE IF NOT EXISTS `db_progra4_proyecto1`.`estudiante` (
  `id_estudiante` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estudiante`),
  INDEX `fk_estudiante_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_progra4_proyecto1`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_progra4_proyecto1`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_progra4_proyecto1`.`estado` ;

CREATE TABLE IF NOT EXISTS `db_progra4_proyecto1`.`estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_progra4_proyecto1`.`matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_progra4_proyecto1`.`matricula` ;

CREATE TABLE IF NOT EXISTS `db_progra4_proyecto1`.`matricula` (
  `estudiante_id` INT NOT NULL,
  `grupo_num` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `estado_id` INT NOT NULL,
  `nota` INT NOT NULL,
  `id_matricula` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_matricula_grupo1_idx` (`grupo_num` ASC, `curso_id` ASC) VISIBLE,
  INDEX `fk_matricula_estado1_idx` (`estado_id` ASC) VISIBLE,
  UNIQUE INDEX `estudiante_id_UNIQUE` (`estudiante_id` ASC) VISIBLE,
  UNIQUE INDEX `grupo_num_UNIQUE` (`grupo_num` ASC) VISIBLE,
  UNIQUE INDEX `curso_id_UNIQUE` (`curso_id` ASC) VISIBLE,
  PRIMARY KEY (`id_matricula`),
  CONSTRAINT `fk_matricula_estudiante1`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `db_progra4_proyecto1`.`estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_grupo1`
    FOREIGN KEY (`grupo_num` , `curso_id`)
    REFERENCES `db_progra4_proyecto1`.`grupo` (`num_grupo` , `curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `db_progra4_proyecto1`.`estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_progra4_proyecto1`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_progra4_proyecto1`.`administrador` ;

CREATE TABLE IF NOT EXISTS `db_progra4_proyecto1`.`administrador` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_administrador`),
  INDEX `fk_administrador_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_administrador_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_progra4_proyecto1`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_progra4_proyecto1`.`especialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_progra4_proyecto1`.`especialidad` ;

CREATE TABLE IF NOT EXISTS `db_progra4_proyecto1`.`especialidad` (
  `profesor_id_profesor` INT NOT NULL,
  `area_tematica_id` INT NOT NULL,
  PRIMARY KEY (`profesor_id_profesor`, `area_tematica_id`),
  INDEX `fk_especialidad_area_tematica1_idx` (`area_tematica_id` ASC) VISIBLE,
  CONSTRAINT `fk_especialidad_profesor1`
    FOREIGN KEY (`profesor_id_profesor`)
    REFERENCES `db_progra4_proyecto1`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_especialidad_area_tematica1`
    FOREIGN KEY (`area_tematica_id`)
    REFERENCES `db_progra4_proyecto1`.`area_tematica` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
