-- MySQL Script generated by MySQL Workbench
-- Thu Apr 29 15:35:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cursosonline
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cursosonline` ;

-- -----------------------------------------------------
-- Schema cursosonline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cursosonline` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `cursosonline` ;

-- -----------------------------------------------------
-- Table `cursosonline`.`area_tematica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursosonline`.`area_tematica` ;

CREATE TABLE IF NOT EXISTS `cursosonline`.`area_tematica` (
  `id_area` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursosonline`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursosonline`.`curso` ;

CREATE TABLE IF NOT EXISTS `cursosonline`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `area_tematica_id` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_curso_area_tematica1_idx` (`area_tematica_id` ASC) VISIBLE,
  CONSTRAINT `fk_curso_area_tematica1`
    FOREIGN KEY (`area_tematica_id`)
    REFERENCES `cursosonline`.`area_tematica` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursosonline`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursosonline`.`rol` ;

CREATE TABLE IF NOT EXISTS `cursosonline`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursosonline`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursosonline`.`usuario` ;

CREATE TABLE IF NOT EXISTS `cursosonline`.`usuario` (
  `id_usuario` VARCHAR(45) NOT NULL,
  `rol_id` INT NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `ultimo_aceso` TIMESTAMP NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_rol_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `cursosonline`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursosonline`.`profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursosonline`.`profesor` ;

CREATE TABLE IF NOT EXISTS `cursosonline`.`profesor` (
  `id_profesor` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_profesor`),
  INDEX `fk_profesor_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_profesor_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cursosonline`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursosonline`.`horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursosonline`.`horario` ;

CREATE TABLE IF NOT EXISTS `cursosonline`.`horario` (
  `seq` INT NOT NULL AUTO_INCREMENT,
  `dia` INT NOT NULL,
  `hora` INT NOT NULL,
  PRIMARY KEY (`seq`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursosonline`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursosonline`.`grupo` ;

CREATE TABLE IF NOT EXISTS `cursosonline`.`grupo` (
  `num_grupo` INT NOT NULL AUTO_INCREMENT,
  `curso_id` INT NOT NULL,
  `profesor_id` INT NOT NULL,
  `horario_seq` INT NOT NULL,
  PRIMARY KEY (`num_grupo`),
  INDEX `fk_grupo_curso1_idx` (`curso_id` ASC) VISIBLE,
  INDEX `fk_grupo_profesor1_idx` (`profesor_id` ASC) VISIBLE,
  INDEX `fk_grupo_horario1_idx` (`horario_seq` ASC) VISIBLE,
  CONSTRAINT `fk_grupo_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `cursosonline`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_profesor1`
    FOREIGN KEY (`profesor_id`)
    REFERENCES `cursosonline`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_horario1`
    FOREIGN KEY (`horario_seq`)
    REFERENCES `cursosonline`.`horario` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursosonline`.`estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursosonline`.`estudiante` ;

CREATE TABLE IF NOT EXISTS `cursosonline`.`estudiante` (
  `id_estudiante` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estudiante`),
  INDEX `fk_estudiante_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cursosonline`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursosonline`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursosonline`.`estado` ;

CREATE TABLE IF NOT EXISTS `cursosonline`.`estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursosonline`.`matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursosonline`.`matricula` ;

CREATE TABLE IF NOT EXISTS `cursosonline`.`matricula` (
  `matricula_id` INT NOT NULL AUTO_INCREMENT,
  `estudiante_id` INT NOT NULL,
  `grupo_num` INT NOT NULL,
  `estado_id` INT NOT NULL,
  `nota` INT NOT NULL,
  INDEX `fk_matricula_estado1_idx` (`estado_id` ASC) VISIBLE,
  INDEX `fk_matricula_grupo1_idx` (`grupo_num` ASC) VISIBLE,
  PRIMARY KEY (`matricula_id`),
  UNIQUE INDEX `estudiante_id_UNIQUE` (`estudiante_id` ASC) VISIBLE,
  UNIQUE INDEX `grupo_num_UNIQUE` (`grupo_num` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_estudiante1`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `cursosonline`.`estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `cursosonline`.`estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_grupo1`
    FOREIGN KEY (`grupo_num`)
    REFERENCES `cursosonline`.`grupo` (`num_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursosonline`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursosonline`.`administrador` ;

CREATE TABLE IF NOT EXISTS `cursosonline`.`administrador` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_administrador`),
  INDEX `fk_administrador_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_administrador_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cursosonline`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursosonline`.`especialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursosonline`.`especialidad` ;

CREATE TABLE IF NOT EXISTS `cursosonline`.`especialidad` (
  `profesor_id_profesor` INT NOT NULL,
  `area_tematica_id` INT NOT NULL,
  `id_especialidad` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_especialidad`),
  INDEX `fk_especialidad_area_tematica1_idx` (`area_tematica_id` ASC) VISIBLE,
  UNIQUE INDEX `area_tematica_id_UNIQUE` (`area_tematica_id` ASC) VISIBLE,
  UNIQUE INDEX `profesor_id_profesor_UNIQUE` (`profesor_id_profesor` ASC) VISIBLE,
  CONSTRAINT `fk_especialidad_profesor1`
    FOREIGN KEY (`profesor_id_profesor`)
    REFERENCES `cursosonline`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_especialidad_area_tematica1`
    FOREIGN KEY (`area_tematica_id`)
    REFERENCES `cursosonline`.`area_tematica` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
